%---------------------------------------------------------------------------------
% yearlym_30runm_ts.m
%---------------------------------------------------------------------------------
%
% smooths an incoming time series with a 30 point running mean
%
% levi silvers                                                           june 2017
%---------------------------------------------------------------------------------

%primary_ts=sw_cre_am4_mn;
%
%tendindex=nyears;
rough_ts=incoming_ts;
clear ts_smooth;
clear idiotbox;
for ti=16:tendindex-15
  ts_smooth(ti-15)=(rough_ts(ti-15)+rough_ts(ti-14)+...
                    rough_ts(ti-13)+rough_ts(ti-12)+...
		    rough_ts(ti-11)+rough_ts(ti-10)+...
		    rough_ts(ti-9)+rough_ts(ti-8)+...
		    rough_ts(ti-7)+rough_ts(ti-6)+...
		    rough_ts(ti-5)+rough_ts(ti-4)+...
		    rough_ts(ti-3)+rough_ts(ti-2)+rough_ts(ti-1)+...
		    rough_ts(ti)+...
		    rough_ts(ti+1)+rough_ts(ti+2)+...
		    rough_ts(ti+3)+rough_ts(ti+4)+...
		    rough_ts(ti+5)+rough_ts(ti+6)+...
		    rough_ts(ti+7)+rough_ts(ti+8)+...
		    rough_ts(ti+9)+rough_ts(ti+10)+...
		    rough_ts(ti+11)+rough_ts(ti+12)+...
		    rough_ts(ti+13)+rough_ts(ti+14)+...
		    rough_ts(ti+15))/31.;
end
idiotbox=ts_smooth;

'one more idiotbox computed'
